### ISSUE TITLE
Можно сокращать конструкторы, вызовом одного конструктора из другого

### ISSUE THREAD

**Issue by MyWayToJavaJunior** [Djasir/EPAM#1]
public Ammunition(long id, String name, double price, double weight, double protection) {
        this.id = generateRandomNumber(1000);
        this.name = name;
        this.price = price;
        this.weight = weight;
    }

    public Ammunition(long id, String name, double price, double weight) {
        this.id = generateRandomNumber(1000);
        this.name = name;
        this.price = price;
        this.weight = weight;
    }

->

    public Ammunition(long id, String name, double price, double weight, double protection) {
        this(generateRandomNumber(1000), name, price, weight);
    }

    public Ammunition(long id, String name, double price, double weight) {
        this.id = generateRandomNumber(1000);
        this.name = name;
        this.price = price;
        this.weight = weight;
    }

**Comment by Djasir** [comment]
Fixed.
